// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcicnqudlgasbwqujtzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjaWNucXVkbGdhc2J3cXVqdHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjc3MDEsImV4cCI6MjA2Mzk0MzcwMX0.C5y1sXj3CqInBEVVhun_IuXFPIyIC_2YRopmfp5IMoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);